Repository petcomputacaoufrgs/hidracpp, pull requests merged in 2021-03, with the labels that each got.

#14 Fix para situação em que botões não respondem ao clique
  src/gui/hidracodeeditor.cpp
Labels: bug

#16 Implementação Inicial de Find & Replace
  src/gui/findreplacedialog.cpp
  src/gui/findreplacedialog.h
  src/gui/findreplacedialog.ui
  src/gui/hidracodeeditor.cpp
  src/gui/hidracodeeditor.h
  src/gui/hidragui.cpp
  src/gui/hidragui.h
  src/gui/hidragui.ui
  src/hidra.pro
Labels: Feature

#13 Template para novos Pull Requests
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  src/core/machine.cpp
  src/core/main.cpp
  src/gui/about.ui
  src/gui/hidragui.cpp
  src/gui/hidrahighlighter.cpp
Labels: enhancement

#19 Fix para a diretiva ORG aceitar valores em hexadecimal
  src/core/machine.cpp
Labels: bug

#20 Config File
  src/core/main.cpp
  src/gui/hidragui.cpp
  src/gui/hidragui.h
  src/gui/hidragui.ui
Labels: Feature
